default_platform(:ios)

TEAM_ID = '56W5SXE4HE'
SCHEME_DEV = 'sample-ios-swift'
BUNDLE_ID_DEV = 'com.monstar-lab.sample-ios-swift'
PROVISIONING_PROFILE_NAME_DEV = 'ML sample ios swift'

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc 'Run unit test.'
  lane :test do
    run_tests(
      device: 'iPhone 8',
      scheme: SCHEME_DEV
    )
  end

  desc 'Build ipa'
  lane :beta do
    # if you can use `match`, you use `match`.
    # setup_provisioning_profiles

    match(
      type: "enterprise",
      readonly: true
    )

    build_app(
      scheme: SCHEME_DEV,
      export_method: 'enterprise',
    )
    message = "Commit: #{ENV['CIRCLE_SHA1']} / #{last_git_commit[:message]}, Build: #{ENV['CIRCLE_BUILD_NUM']}"
    deploygate(
      message: message
    )
  end

  private_lane :setup_provisioning_profiles do |options|
    next unless Helper.ci?

    `curl -OL https://developer.apple.com/certificationauthority/AppleWWDRCA.cer`
    import_certificate(
      keychain_name: 'fastlane_tmp_keychain',
      certificate_path: 'certificates/dist.p12',
      certificate_password: ENV['IOS_CERTIFICATES_KEY_PASSWORD'],
      keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD'])
    import_certificate(
      keychain_name: 'fastlane_tmp_keychain',
      certificate_path: 'fastlane/AppleWWDRCA.cer',
      keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD'])

    Dir.glob('../certificates/*.mobileprovision').each {|filename|
      puts filename
      FastlaneCore::ProvisioningProfile.install(filename)
    }
  end
end
